### ISSUE TITLE
Steam authentication regularly gets lost + clicking the notification takes user to the wrong place

### ISSUE THREAD

**Issue by Jeshibu** [Lacro59/playnite-successstory-plugin#408] opened 2023-10-29 14:10 UTC
The Steam authentication for SuccessStory regularly needs to be re-done by the user, while this is not the case for the Steam plugin itself. Maybe some token refresh thing? Also clicking the error notification takes the user to the Steam plugin settings instead of the SuccessStory settings.

**Comment by SonnyRocket** [comment] 2023-10-30 07:04
I can confirm this has continually happened for the past few weeks now and and it's getting really annoying to keep 'dismissing' the notification only for it to reappear the next time Playnite is launched.

**Comment by ivanlorusso** [comment] 2023-11-07 19:03
I can confirm too, syncing anything from Steam (or GOG) is pretty much impossible, even if I'm authenticated I get a 401 error.

**Comment by marcovirtual** [comment] 2023-11-11 05:06
The same thing is happening to me. No Steam achievements are being synced. But it was not like this in the past. Don't know what might been causing this.

**Comment by GitDoric** [comment] 2023-11-11 13:51
Same issue here.

**Comment by Gerren** [comment] 2023-11-15 08:24
I'm not sure, if it is the same thing, but no matter the combination of Steam configuration in SuccessStory I choose, I get either "The Steam user is not authenticated" (which he is, the integration says so) or "No Steam configuration and/or API key", which is also false, since the Steam integration functions just fine.

**Comment by Jeshibu** [comment] 2023-11-15 08:26
@Gerren you need to authenticate under `main menu > Add-ons > Extension settings > Generic > SuccessStory > Library`, not via the Steam plugin.

**Comment by Gerren** [comment] 2023-11-16 15:58
@Jeshibu heyyy, that was it. No other issue then. Thanks.

**Comment by scooterama** [comment] 2023-11-20 14:31
the API Key down't get saved even if put in manually

**Comment by ciaron88** [comment] 2023-12-23 10:34
STLL happening for me! won't save/keep the authentication Any update on when/if this will be fixed??? because i am about to yeet this s*** plugin in to the sun!

**Comment by Lacro59** [comment] 2024-06-26 10:23
This is a test version for Steam achievements.
Can you test if you have a problem with Steam?
Be careful if you post a log file because it is a debug version with potential personal information.
[playnite-successstory-plugin_3_1_7_dev.zip](https://github.com/user-attachments/files/15986442/playnite-successstory-plugin_3_1_7_dev.zip)

**Closed** 2024-08-12 11:39 UTC
Labels: bug

**Comment by ciaron88** [comment] 2024-11-14 13:23
This is still happening for me as of 3.2.2. Private account with API key. Always loses the authentation...
